repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: ^.*\b(charts)\b.*$
      - id: check-added-large-files
      - id: detect-private-key
      - id: check-docstring-first
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: "v5.7.0"
    hooks:
      - id: isort
        args: ["--profile", "black"]
        types: [file, python]
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        args: ["--line-length", "80"]
        exclude: ^.*\b(migrations)\b.*$
        types: [file, python]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        additional_dependencies:
          [
            "flake8-comprehensions",
            "flake8-debugger",
            "flake8-eradicate",
            "flake8-mutable",
          ]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
        exclude: ^.*\b(charts)\b.*$
  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.0"
    hooks:
      - id: bandit