name: Integration - {{ cookiecutter.project_name }}

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    name: Tests on ${{ '{{' }} matrix.python-version {{ '}}' }}
    env:
      PYTHON_VERSION: ${{ '{{' }} matrix.python-version {{ '}}' }}
      ENV: dev
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python and Tox
        uses: actions/setup-python@v2
        with:
          python-version: ${{ '{{' }} matrix.python-version {{ '}}' }}
          architecture: x64
      - name: Build docker image
        run: docker build . -t igormcsouza/{{ cookiecutter.project_name }}:test
      - name: Run tests using TOX
        run: |
          docker run igormcsouza/{{ cookiecutter.project_name }}:test tox -e py
